query SearchTotesDashboard($page: Float!, $size: Float!) {
    totes(page: $page, size: $size) {
        id
        name
        color
        description
        bannerURL
        price
        rating
        size
        style
        inStock
        isBestSeller
        isNewArrival
        material
    }
}

query GetQuickViewTote($id: String!) {
    tote(id: $id) {
        id
        name
        color
        description
        bannerURL
        price
        rating
        size
        style
        inStock
        isBestSeller
        isNewArrival
        material
    }
}
